### ISSUE TITLE
Consider a more liberal license

### ISSUE THREAD

**Issue by jni** [bionanopatterning/pyGPUreg#1]
Hi @smurkel, and thanks for sharing this very cool work!

The GPL license is quite uncommon in the scientific Python world. I am wondering whether you would reconsider licensing it using a more liberal license such as (from most liberal to least liberal) MIT, BSD-3-clause, Apache 2.0, MPL-2.0, or LGPLv3. All of these licenses would enable more liberally licensed code to *import* your code and use it. With GPLv3, only other GPLv3 code can use it, which is rare in the Python ecosystem.

Obviously this is a personal choice and I am not dogmatic about this. Philosophically I like MPL-2.0 best, but my main guiding principle is "when in Rome, do as the Romans do."

Feel free to close this if you have considered all those factors and prefer GPL anyway. Thank you! 🙏

**Comment by smurkel** [comment]
Hi @jni,

Thanks for the feedback! We were aiming for a 'anyone can use this for anything, but we'd be disappointed if you tried to sell it' type of license. I'll have a look at MPL-2.0 and the others you've mentioned and change the license to one that is more liberal.

**Comment by bionanopatterning** [comment]
License is now MPL-2.0!

**Comment by jni** [comment]
Love it! Thank you!

> anyone can use this for anything, but we'd be disappointed if you tried to sell it

yes, that is my reading of MPL-2.0 also! 😃
